In [ ]:
# Compute pseudo-inverse of a matrix using SVD.

In [1]:
import numpy as np

M = np.array([[1,2,3,4],[2,4,8,0],[12,-8,-12,0]])
print('M (3x4):\n', M)

M (3x4):
 [[  1   2   3   4]
 [  2   4   8   0]
 [ 12  -8 -12   0]]


In [2]:
# Compute SVD
U, E, Vt = np.linalg.svd(M)
print('\nU (3x3):\n', U)
print('\nE (non-zero Sigma_ii in diag form):\n', E)
print('\nVt (4x4):\n', Vt)


U (3x3):
 [[-0.13334471 -0.47047655 -0.8722792 ]
 [-0.32814963 -0.8095341   0.48679806]
 [ 0.93516683 -0.35115005  0.04643961]]

E (non-zero Sigma_ii in diag form):
 [19.85439808  7.65819068  3.62698118]

Vt (4x4):
 [[ 0.52544318 -0.45635343 -0.71758575 -0.02686452]
 [-0.82308545 -0.17887896 -0.47973498 -0.2457377 ]
 [ 0.18158138 -0.04656298  0.19858707 -0.96198922]
 [-0.11605177 -0.87038828  0.46420708  0.11605177]]


In [3]:
# Check that we can use SVD to reconstruct the original matrix
Reconstructed_M = np.zeros((3,4))

for i in range(len(E)):
    Reconstructed_M += ( E[i] * np.dot(U[:,i].reshape(3,1), Vt[i,:].reshape(1,4)) )
    
print('Reconstructed_M (3x4):\n', Reconstructed_M)
print('\nElement-wise squared reconstruction error (3x4):\n', (M - Reconstructed_M)**2)

Reconstructed_M (3x4):
 [[ 1.00000000e+00  2.00000000e+00  3.00000000e+00  4.00000000e+00]
 [ 2.00000000e+00  4.00000000e+00  8.00000000e+00 -1.99840144e-15]
 [ 1.20000000e+01 -8.00000000e+00 -1.20000000e+01  2.16493490e-15]]

Element-wise squared reconstruction error (3x4):
 [[1.97215226e-31 1.97215226e-31 7.88860905e-31 1.77493704e-30]
 [1.77493704e-30 1.26217745e-29 3.15544362e-30 3.99360833e-30]
 [1.13595970e-28 7.88860905e-29 1.26217745e-29 4.68694311e-30]]


In [4]:
# Check U and V are orthonormal matrices
print('U is orthonormal (U U^T):\n', np.dot(U, U.T))
print('\nV is orthonormal (V V^T):\n', np.dot(Vt, Vt.T))

U is orthonormal (U U^T):
 [[ 1.00000000e+00  2.16270566e-16 -2.22650796e-17]
 [ 2.16270566e-16  1.00000000e+00 -1.09786322e-17]
 [-2.22650796e-17 -1.09786322e-17  1.00000000e+00]]

V is orthonormal (V V^T):
 [[ 1.00000000e+00 -1.98998035e-16 -1.37767807e-16  8.30952129e-17]
 [-1.98998035e-16  1.00000000e+00 -1.12857076e-16 -1.49649823e-16]
 [-1.37767807e-16 -1.12857076e-16  1.00000000e+00  6.08494550e-17]
 [ 8.30952129e-17 -1.49649823e-16  6.08494550e-17  1.00000000e+00]]


In [5]:
# Compute Σ+
E_plus = np.diag( 1./E )
E_plus = np.vstack( (E_plus, np.zeros((1,3)) ) )
print('E_plus:\n', E_plus)

E_plus:
 [[0.05036667 0.         0.        ]
 [0.         0.13057915 0.        ]
 [0.         0.         0.27571138]
 [0.         0.         0.        ]]


In [6]:
# Compute M+
M_plus = np.dot(Vt.T, np.dot(E_plus, U.T))
print('M_plus (4x3):\n', M_plus)

M_plus (4x3):
 [[ 0.003367    0.1026936   0.06481481]
 [ 0.02525253  0.02020202 -0.01388889]
 [-0.01346801  0.08922559 -0.00925926]
 [ 0.246633   -0.1026936  -0.00231481]]


In [7]:
# Confirm MM+ is an identity matrix
print('M M_plus (should be an identity matrix):\n', np.dot(M, M_plus))

M M_plus (should be an identity matrix):
 [[ 1.00000000e+00  1.11022302e-16  3.46944695e-18]
 [ 3.74700271e-16  1.00000000e+00 -5.55111512e-17]
 [ 3.53883589e-16 -5.55111512e-17  1.00000000e+00]]


In [8]:
# Compute pseudo inverse using numpy.linalg.pinv
print('Pseudo-inverse using pinv:\n',np.linalg.pinv(M))

Pseudo-inverse using pinv:
 [[ 0.003367    0.1026936   0.06481481]
 [ 0.02525253  0.02020202 -0.01388889]
 [-0.01346801  0.08922559 -0.00925926]
 [ 0.246633   -0.1026936  -0.00231481]]
