In [1]:
import numpy as np
import math
from scipy import linalg

In [2]:
# Computing representation of a line from two points in homogeneous coordinates
ah = np.array([1,2,1])
bh = np.array([4,3,1])

l = np.cross(ah, bh)
print('l = {}'.format(l))
print('Computed line passes through point a: {}'.format(math.isclose(np.dot(ah, l), 0.0)))
print('Computed line passes through point b: {}'.format(math.isclose(np.dot(bh, l), 0.0)))

l = [-1  3 -5]
Computed line passes through point a: True
Computed line passes through point b: True


In [3]:
# Finding the intersection of two lines using homogeneous coordinates
l1 = np.array([3,-1,7])
l2 = np.array([2,-1,1])

ph = np.cross(l1, l2)
print('ph = {}'.format(ph))

p = ph[:2] / ph[2]
print('p = {}'.format(p))
print('Point p sits on l1: {}'.format(math.isclose(np.dot(l1, np.append(p,[1])), 0.0)))
print('Point p sits on l2: {}'.format(math.isclose(np.dot(l2, np.append(p,[1])), 0.0)))

ph = [ 6 11 -1]
p = [ -6. -11.]
Point p sits on l1: True
Point p sits on l2: True


In [4]:
# Computing point of intersection of two lines using homogeneous coordinates
ah = np.array([3,-1,7])
bh = np.array([3,-1,-3])

p = np.cross(ah, bh)
print('p = {}'.format(p))
print('Homogenous component of p: w = {}'.format(p[2]))
print('Computed line passes through point a: {}'.format(math.isclose(np.dot(ah, p), 0.0)))
print('Computed line passes through point b: {}'.format(math.isclose(np.dot(bh, p), 0.0)))

p = [10 30  0]
Homogenous component of p: w = 0
Computed line passes through point a: True
Computed line passes through point b: True


In [ ]:
# Determining camera parameters from a projection matrix

In [5]:
P = np.array([[3.53553e2, 3.39645e2, 2.77744e2, -1.44946e6],
              [-1.03528e2, 2.33212e1, 4.59607e2, -6.32525e5],
              [7.07107e-1, -3.53553e-1, 6.12372e-1, -9.18559e2]]) 

In [6]:
# Let's break P into constituents parts
M = P[:3,:3]
print(f'M = {M}')

M_inv = np.linalg.inv(M)
print(f'M_inv = {M_inv}')

p_4 = P[:,-1]
print(f'p_4 = {p_4}')

C = - np.dot(M_inv, p_4)
print(f'Center of this camera is {C}')

M = [[ 3.53553e+02  3.39645e+02  2.77744e+02]
 [-1.03528e+02  2.33212e+01  4.59607e+02]
 [ 7.07107e-01 -3.53553e-01  6.12372e-01]]
M_inv = [[ 8.83882084e-04 -1.53092925e-03  7.48128351e-01]
 [ 1.94194195e-03  1.00556004e-04 -9.56247129e-01]
 [ 1.00560104e-04  1.82582265e-03  2.17039911e-01]]
p_4 = [-1.44946e+06 -6.32525e+05 -9.18559e+02]
Center of this camera is [1000.00073079 2000.001952   1500.00028314]


In [7]:
# M is given, how to find K and R?
# Use RQ-decomposition
K, R = linalg.rq(M)

print(f'K = {K}')
print(f'R = {R}')

K = [[ 468.16467128  -91.22505222 -300.00001631]
 [   0.         -427.20086371 -199.99985412]
 [   0.            0.           -0.99999975]]
R = [[ 0.41380237  0.90914861  0.04707869]
 [ 0.57338211 -0.22011137 -0.78916661]
 [-0.70710718  0.35355309 -0.61237215]]


In [ ]:
# Confirm R is a rotation matrix, i.e., R^TR = I

In [8]:
np.isclose(np.dot(R[:,0], R[:,1]), 0)

True

In [9]:
np.dot(R, R.T)

array([[ 1.00000000e+00, -2.71323943e-16, -4.13630351e-17],
       [-2.71323943e-16,  1.00000000e+00,  1.80002593e-16],
       [-4.13630351e-17,  1.80002593e-16,  1.00000000e+00]])

In [10]:
# Confirm K is an upper-diagonal matrix
K

array([[ 468.16467128,  -91.22505222, -300.00001631],
       [   0.        , -427.20086371, -199.99985412],
       [   0.        ,    0.        ,   -0.99999975]])

In [ ]:
# Make diagonal entries of K positive

In [11]:
np.diag(K)

array([ 468.16467128, -427.20086371,   -0.99999975])

In [12]:
np.sign(np.diag(K))

array([ 1., -1., -1.])

In [13]:
F = np.diag(np.sign(np.diag(K)))
print(f'F = {F}')

F = [[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]


In [14]:
np.dot(F, F) # FORTRAN IDENTITY

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Use M = K ∗ R = (K ∗ F) ∗ (F ∗ R)

In [15]:
new_K = np.dot(K, F)
print(f'new_K = {new_K}')

new_K = [[468.16467128  91.22505222 300.00001631]
 [  0.         427.20086371 199.99985412]
 [  0.           0.           0.99999975]]


In [16]:
new_R = np.dot(F, R)
print(f'new_R = {new_R}')

new_R = [[ 0.41380237  0.90914861  0.04707869]
 [-0.57338211  0.22011137  0.78916661]
 [ 0.70710718 -0.35355309  0.61237215]]
