In [88]:
import numpy as np

In [89]:
img = [[1, 2, 3, 4], [0, -1, 2, 8], [9, -8, -3, 1]]
img = np.array(img)
img

array([[ 1,  2,  3,  4],
       [ 0, -1,  2,  8],
       [ 9, -8, -3,  1]])

In [90]:
# This can work from 1d to n-d
#   only need to add extra for-loop for each dimension and change the img slicing
def img_integral_2d(img):
    h, w = img.shape
    integral_img = np.zeros((h, w))
    for i in range(h):
        for j in range(w):
            integral_img[i, j] = np.sum(img[:i+1, :j+1])
    return integral_img

integral_img = img_integral_2d(img)
integral_img

array([[ 1.,  3.,  6., 10.],
       [ 1.,  2.,  7., 19.],
       [10.,  3.,  5., 18.]])

In [94]:
integral_img[1:3, 1:4]

array([[ 2.,  7., 19.],
       [ 3.,  5., 18.]])

In [108]:
# I[x1:x2, y1:y2]
# Summation = A - B - C + D
def integral_summation_2d(img, x1, x2, y1, y2):
    sum = img[x2-1, y2-1]
    if x1 != 0:
        sum -= img[x1-1, y2-1]
    if y1 != 0:
        sum -= img[x2-1, y1-1]
    if x1 != 0 and y1 != 0:
        sum += img[x1-1, y1-1]
    return sum

integral_summation_2d(integral_img, 1, 3, 1, 4)

-1.0

In [92]:
unit_tensor = np.ones((3, 3, 3))
unit_tensor

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [93]:
def img_integral_3d(img):
    h, w, z = img.shape
    integral_img = np.zeros((h, w, z))
    for i in range(h):
        for j in range(w):
            for k in range(z):
                integral_img[i, j, k] = np.sum(img[:i+1, :j+1, :k+1])
    return integral_img

img_integral_3d(unit_tensor)

array([[[ 1.,  2.,  3.],
        [ 2.,  4.,  6.],
        [ 3.,  6.,  9.]],

       [[ 2.,  4.,  6.],
        [ 4.,  8., 12.],
        [ 6., 12., 18.]],

       [[ 3.,  6.,  9.],
        [ 6., 12., 18.],
        [ 9., 18., 27.]]])